//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitBull.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oneri
    {
        public int ID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public Nullable<int> AntrenmanID { get; set; }
        public Nullable<int> DiyetID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual Antrenman Antrenman { get; set; }
        public virtual Diyet Diyet { get; set; }
        public virtual Kategori Kategori { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
